/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ["class"],
  important: "#app",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b2c5ff",
        "inverse-surface": "#303030",
        secondary: "#3e58b4",
        "outline-variant": "#c4c6d4",
        "surface-variant": "#e2e2e2",
        outline: "#747683",
        "inverse-on-surface": "#f1f1f1",
        "on-secondary-fixed": "#001452",
        "surface-dim": "#dadada",
        "on-error": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "on-primary-fixed": "#001848",
        "tertiary-fixed": "#96fa7a",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#dde1ff",
        "secondary-fixed-dim": "#b7c4ff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#3059b7",
        "surface-container": "#eeeeee",
        "on-surface-variant": "#434652",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#233f9b",
        background: "#f9f9f9",
        "surface-container-low": "#f3f3f3",
        primary: "#1847a4", // Dark Blue from logo
        "on-secondary-container": "#10308d",
        "primary-fixed": "#dae2ff",
        "on-tertiary-fixed-variant": "#0b5300",
        "tertiary-container": "#147500",
        "tertiary-fixed-dim": "#7bdd61",
        "on-primary-fixed-variant": "#0b409e",
        "on-primary-container": "#dbe2ff",
        surface: "#f9f9f9",
        "primary-container": "#1e50a2", // Mid Blue from logo
        "on-tertiary-fixed": "#022100",
        "on-background": "#1b1b1b",
        error: "#ba1a1a",
        "surface-bright": "#f9f9f9",
        tertiary: "#49a078", // Green from logo
        "on-secondary": "#ffffff",
        "on-surface": "#1b1b1b",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#869eff",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary-container": "#96fa7a",
        "inverse-primary": "#b2c5ff",
      },
      fontFamily: {
        headline: ["var(--font-source-sans)"],
        body: ["var(--font-source-sans)"],
        label: ["var(--font-source-sans)"],
        inter: ["var(--font-inter)"],
        poppins: ["var(--font-poppins)"],
        roboto: ["var(--font-roboto)"],
      },
    },
  },
  plugins: [],
};

export default config;
